gui/nlp_v1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sim_v1/', include('sim_v1.urls', namespace = 'sim_v1')),
    path('home_v1/', include('home_v1.urls', namespace = 'home_v1')),
    url(r'^sum_v1/', include('sum_v1.urls', namespace='sum_v1')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gui/sum_v1/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'sum_v1'
urlpatterns = [
    url(r'^clear/$', views.clear_database, name='clear_database'),
    url(r'^upload/$', views.Upload.as_view(), name='upload'),
    path('summarize', views.Summarize, name='summarize'),
    path('sum_words', views.sum_words, name='sum_words'),
]

gui/sum_v1/models.py
from __future__ import unicode_literals

from django.db import models


class File_upload(models.Model):
    file = models.FileField(upload_to='sum_v1/upload', max_length = 500, blank = True)
    sum_words = models.IntegerField(default = 200, blank = True)

class SummaryRes(models.Model):
    doc = models.CharField(max_length = 200)
    summary = models.TextField()

    def __str__(self):
           return self.url

gui/sum_v1/forms.py
from django import forms

from .models import File_upload


class File_uploadForm(forms.ModelForm):
    class Meta:
        model = File_upload
        fields = ('file','sum_words',)

gui/sum_v1/views.py
import time
import os

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View
from django.conf import settings


from .forms import File_uploadForm
from .models import File_upload, SummaryRes

from sim_v1.textsummary import TEXTSummary
summary_document_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)),'media','sum_v1','upload')
#summary_document_dir = r'C:\Users\ERDIG\Dropbox\Python\nlp_v1\media\sum_v1\upload'

summary_extraction_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)),'media','sum_v1','temp')
#summary_extraction_dir = r'C:\Users\ERDIG\Dropbox\Python\nlp_v1\media\sum_v1\temp'

summary_ratio = 0.01

class Upload(View):
    def post(self, request):
        time.sleep(1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.

        form = File_uploadForm(self.request.POST, self.request.FILES)

        print(form.errors)

        if form.is_valid():

            document = form.save()
            data = {'is_valid': True, 'name': document.file.name, 'url': document.file.url}

        else:
            data = {'is_valid': False}

        return JsonResponse(data)

    def get(self, request):

        for document in File_upload.objects.all():
            document.file.delete()
            document.delete()

        doc_list = File_upload.objects.all()

        form = File_uploadForm()

        return render(self.request, 'upload.html', {'documents': doc_list, 'form': form,})

def sum_words(request):
    if request.method == 'POST':

        form = File_uploadForm(request.POST)

        if form.is_valid():
            form.save()
            sum_words = form.cleaned_data['sum_words']
            request.session['sum_words'] = sum_words

        else:
            pass
    else:
        pass

    return redirect('sum_v1:summarize')

def clear_database(request):
    for document in File_upload.objects.all():
        document.file.delete()
        document.delete()
    return redirect(request.POST.get('next'))

def Summarize(request):
    SummaryRes.objects.all().delete()

    summary_word_count = request.session['sum_words']

    for document in os.listdir(summary_document_dir):

        for filename in os.listdir(summary_extraction_dir):
            os.remove(os.path.join(summary_extraction_dir, filename))

        text_dir = os.path.join(summary_document_dir, document)

        summary = TEXTSummary(text_dir, summary_extraction_dir, summary_ratio, summary_word_count)
        summary.textextraction()
        summary.summary()

        SummaryRes.objects.create(doc = document, summary = summary.summary)

    results = SummaryRes.objects.all()

    return render(request, 'summarize.html', {'results': results})

gui/sum_v1/templates/sum_v1_base.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1 class="tool-heading">
      Summary tool
    </h1>
  </div>

  <div class="col-md-9">
    {% block photos_content %}
    {% endblock %}
  </div>

{% endblock %}

gui/sum_v1/templates/summarize.html
{% extends 'sum_v1_base.html' %}

{% load static %}

{% block javascript %}
{% endblock %}

{% block photos_content %}
	<h3>Results</h3>
	{% for result in results %}
		<div class="results">
			<h4>{{ result.doc }}</h4>
			<p>{{ result.summary }}</p>
		</div>
	{% endfor %}

	<div class="back-button">
		<form action="{% url 'sum_v1:upload' %}">
			{% csrf_token %}
			<button type="submit" class="btn btn-primary pull-left">
				<span class="	glyphicon glyphicon-step-backward"></span> Back
			</button>
		</form>
	</div>

{% endblock %}

gui/sum_v1/templates/upload.html
{% extends 'sum_v1_base.html' %}

{% load static %}

{% block javascript %}
	{# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

	{# PHOTOS PAGE SCRIPTS #}
	<!--script src="{% static 'js/basic-upload.js' %}"></script-->
	<script src="{% static 'js/progress-bar-upload.js' %}"></script>
{% endblock %}

{% block photos_content %}
	<div class="well text-muted text-center" style="padding-top: 4rem; padding-bottom: 4rem;">
		<span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
		<h3>Drop Documents Here to Upload</h3>
	</div>
	<div style="margin-bottom: 20px;">
		<form method="post" action="{% url 'sum_v1:clear_database' %}">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ request.path }}">
			<button type="submit" class="btn btn-danger pull-right">
				<span class="glyphicon glyphicon-trash"></span> Remove uploaded documents
			</button>
		</form>

		<form method="post" enctype="multipart/form-data">
	  	<button type="button" class="btn btn-primary js-upload-photos">
	    	<span class="glyphicon glyphicon-cloud-upload"></span> or choose documents to upload
	    </button>
	    <input id="fileupload" type="file" name="file" multiple
	           style="display: none;"
	           data-url="{% url 'sum_v1:upload' %}"
	           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
		</form>
	</div>

	<div>
	  <table id="gallery" class="table table-bordered">
	    <thead>
	      <tr>
	        <th>Uploaded documents</th>
	      </tr>
	    </thead>
	    <tbody>
	    	{% for document in documents %}
	      	<tr>
	         <td><a href="{{ document.file.url }}">{{ document.file.name }}</a></td>
	        </tr>
	      {% endfor %}
	    </tbody>
	  </table>
	</div>

		<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
	    <div class="modal-dialog">
	      <div class="modal-content">
	        <div class="modal-header">
	          <h4 class="modal-title">Uploading...</h4>
	        </div>
	        <div class="modal-body">
	          <div class="progress">
	            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>

	<div>
		<form method="post" action="{% url 'sum_v1:sum_words' %}">
			{% csrf_token %}
			<label for="{{ form.word_count.id_for_label }}">Number of words in each summary:</label>
			{{ form.sum_words }}
			<button type="submit" class="btn btn-success pull-right">
				<span class="glyphicon glyphicon-ok"></span> Generate summaries
			</button>
		</form>
	</div>

{% endblock %}