gui/home_v1/urls.py
from django.urls import path

from . import views

app_name = 'home_v1'
urlpatterns = [
    path('index', views.index, name = 'index')
]

gui/nlp_v1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sim_v1/', include('sim_v1.urls', namespace = 'sim_v1')),
    path('home_v1/', include('home_v1.urls', namespace = 'home_v1')),
    url(r'^sum_v1/', include('sum_v1.urls', namespace='sum_v1')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gui/sim_v1/urls.py
from django.urls import path

from . import views

app_name = 'sim_v1'
urlpatterns = [
	path('calculate', views.calculate, name = 'calculate'),
    path('upload', views.model_form_upload, name = 'upload')
]

gui/home_v1/models.py
from django.db import models

# Create your models here.

gui/home_v1/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

gui/home_v1/templates/base.html
{% load static %}

<body>
    <head>
      <!-- Required meta tags -->
      <!--meta charset="utf-8"-->
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
	  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>NLP toolbox</title>
  </head>

	<div class="page-header">
		<h1><a href={% url 'home_v1:index' %}>Natural Language Processing toolbox</a></h1>
		<p>Version: 1.0</p>
	</div>

	<div class="content-container">
		{% block content %}
		{% endblock %}
	</div>
  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block javascript %}
  {% endblock %}
</body>

gui/home_v1/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="tool-heading">
	<h1>Tools index</h1>
	<h2><a href={% url 'sim_v1:upload' %}>Similarity search tool</a></h2>
	<p>A tool for finding similar documents. </p>
	<h2><a href={% url 'sum_v1:upload' %}>Summary tool</a></h2>
	<p>A tool for generating automatic summaries. </p>
</div>

{% endblock %}